apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-karmabot-disk
  namespace: mattermost-bots
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gcepd
---